
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package FileManager;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Name = 2;
  public static final int error = 1;
  public static final int Enter = 6;
  public static final int codeD = 3;
  public static final int coma = 5;
  public static final int EOF = 0;
  public static final int cost = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Name",
  "codeD",
  "cost",
  "coma",
  "Enter"
  };
}

